# Generated by Django 3.2.7 on 2021-09-29 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_insurance_id', models.CharField(blank=True, max_length=7)),
                ('annual_venue_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_venue_fee_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='clients.gender')),
                ('license', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='clients.license')),
            ],
        ),
    ]
