# Generated by Django 3.2.7 on 2021-10-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['client']},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['license']},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='gender',
            old_name='name',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='name',
            new_name='license',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location',
        ),
    ]
