# Generated by Django 3.2.7 on 2021-10-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20211002_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='license',
        ),
        migrations.AddField(
            model_name='client',
            name='license',
            field=models.ManyToManyField(blank=True, to='clients.License'),
        ),
    ]
