# Generated by Django 3.2.7 on 2021-10-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20211002_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ['gender']},
        ),
    ]
