# Generated by Django 3.2.7 on 2021-11-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_gender_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='description',
            new_name='detail',
        ),
        migrations.RemoveField(
            model_name='client',
            name='annual_venue_fee',
        ),
        migrations.RemoveField(
            model_name='client',
            name='annual_venue_fee_paid',
        ),
        migrations.RemoveField(
            model_name='client',
            name='paid',
        ),
        migrations.AddField(
            model_name='license',
            name='vending_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='client',
            name='national_insurance_id',
            field=models.CharField(blank=True, max_length=7, verbose_name='NIC'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.client')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
