# Generated by Django 3.2.7 on 2021-11-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20211109_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
