# Generated by Django 3.2.7 on 2021-11-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_payment_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
