# Generated by Django 3.2.7 on 2021-11-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_payment_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='balance',
        ),
    ]
