# Generated by Django 3.2.7 on 2021-10-10 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_gender_options'),
        ('payments', '0002_alter_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.client'),
        ),
    ]
